spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: always
  kafka:
    consumer:
      group-id: monitoring
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer