spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: always
  kafka:
    consumer:
      group-id: monitoring
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: com.monitoring.kafka.message
#        spring.json.use.type.headers: false
#        spring.json.value.default.type: com.monitoring.kafka.message.KafkaMessage
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer